name: 'mashburn_analytics'
version: '1.0.0'
config-version: 2

profile: 'mashburn_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  mashburn_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      customer:
        +schema: marts
      product:
        +schema: marts
      channel:
        +schema: marts
      returns:
        +schema: marts
